#
# Author: chengyang@supermap.com
# Date: 2019-02-20
#

version: '2'

volumes:
    orderer.atlchain.com:
    peer0.orga.atlchain.com:
    peer1.orga.atlchain.com:
    peer0.orgb.atlchain.com:
    peer1.orgb.atlchain.com:

networks:
    byfn:
services:
    ca0:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-orga
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.orga.atlchain.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/1d542d1afc845ced6f8ce844b2996d6f6463aa679944c5454690b8567b0b9fe1_sk
        ports:
            - "7054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.orga.atlchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/1d542d1afc845ced6f8ce844b2996d6f6463aa679944c5454690b8567b0b9fe1_sk -b admin:adminpw -d'
        volumes:
            - ./crypto-config/peerOrganizations/orga.atlchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca_peerOrgA
        networks:
            - byfn

    ca1:
        image: hyperledger/fabric-ca:$IMAGE_TAG
        environment:
            - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
            - FABRIC_CA_SERVER_CA_NAME=ca-orgb
            - FABRIC_CA_SERVER_TLS_ENABLED=true
            - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.orgb.atlchain.com-cert.pem
            - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/61e87b18f746f8626afe0b157b7be52f57c7a0af8d9357cfe7a006075270f796_sk
        ports:
            - "8054:7054"
        command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.orgb.atlchain.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/61e87b18f746f8626afe0b157b7be52f57c7a0af8d9357cfe7a006075270f796_sk -b admin:adminpw -d'
        volumes:
            - ./crypto-config/peerOrganizations/orgb.atlchain.com/ca/:/etc/hyperledger/fabric-ca-server-config
        container_name: ca_peerOrgB
        networks:
            - byfn

    orderer.atlchain.com:
        extends:
          file:   base/docker-compose-base.yaml
          service: orderer.atlchain.com
        container_name: orderer.atlchain.com
        networks:
            - byfn

    peer0.orga.atlchain.com:
        container_name: peer0.orga.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer0.orga.atlchain.com
        networks:
            - byfn

    peer1.orga.atlchain.com:
        container_name: peer1.orga.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer1.orga.atlchain.com
        networks:
            - byfn

    peer0.orgb.atlchain.com:
        container_name: peer0.orgb.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer0.orgb.atlchain.com
        networks:
            - byfn

    peer1.orgb.atlchain.com:
        container_name: peer1.orgb.atlchain.com
        extends:
            file:  base/docker-compose-base.yaml
            service: peer1.orgb.atlchain.com
        networks:
            - byfn
