Organizations:
  - &OrgOrderer
      Name: OrgOrderer
      ID: OrgOrderer
      MSPDir: /home/stone/Documents/ATL/ATLab-ATLChain/config/crypto-config/ordererOrganizations/cystone.me/msp
      Policies:
        Readers:
            Type: Signature
            Rule: "OR('OrgOrderer.member')"
        Writers:
            Type: Signature
            Rule: "OR('OrgOrderer.member')"
        Admins:
            Type: Signature
            Rule: "OR('OrgOrderer.admin')"

  - &OrgA
      Name: OrgA
      ID: OrgA
      MSPDir: /home/stone/Documents/ATL/ATLab-ATLChain/config/crypto-config/peerOrganizations/orga.cystone.me/msp
      Policies:
        Readers:
            Type: Signature
            Rule: "OR('OrgA.admin', 'OrgA.peer', 'OrgA.client')"
        Writers:
            Type: Signature
            Rule: "OR('OrgA.admin')"
        Admins:
            Type: Signature
            Rule: "OR('OrgA.admin')"
      AnchorPeers:
        - Host: peer0.orga.cystone.me
          Port: 7051

  - &OrgB
      Name: OrgB
      ID: OrgB
      MSPDir: /home/stone/Documents/ATL/ATLab-ATLChain/config/crypto-config/peerOrganizations/orgb.cystone.me/msp
      Policies:
        Readers:
            Type: Signature
            Rule: "OR('OrgB.admin', 'OrgB.peer', 'OrgB.client')"
        Writers:
            Type: Signature
            Rule: "OR('OrgB.admin', 'OrgB.client')"
        Admins:
            Type: Signature
            Rule: "OR('OrgB.admin')"
      AnchorPeers:
        - Host: peer0.orgb.cystone.me
          Port: 7051

Capabilities:
    Channel: &ChannelCapabilities
        V1_1: true
    Orderer: &OrdererCapabilities
        V1_1: true
    Application: &ApplicationCapabilities
        V1_2: true

Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
    - orderer.cystone.me:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 98 MB
    PreferredMaxBytes: 512 KB
  MaxChannels: 0
  Kafka:
    Brokers:
        - 127.0.0.1:9092
  Organizations:
  Policies:
      Readers:
          Type: ImplicitMeta
          Rule: "ANY Readers"
      Writers:
          Type: ImplicitMeta
          Rule: "ANY Writers"
      Admins:
          Type: ImplicitMeta
          Rule: "MAJORITY Admins"
      BlockValidation:
          Type: ImplicitMeta
          Rule: "ANY Writers"
  Capabilities:
      <<: *OrdererCapabilities

Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

Profiles:
  OrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrgOrderer
    Consortiums:
      SampleConsortium:
        Organizations:
          - *OrgA
          - *OrgB

  ChannelForTx:
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *OrgA
        - *OrgB
