OrdererOrgs:
  - Name: Orderer
    Domain: cystone.me
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: OrgA
    Domain: orga.cystone.me
    EnableNodeOUs: true
    Template:
      Count: 2

    Users:
      Count: 2

  - Name: OrgB
    Domain: orgb.cystone.me
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 2
