OrdererOrgs:
  - Name: Orderer
    Domain: supermapchain.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: OrgA
    Domain: orga.supermapchain.com
    Template:
      Count: 1
    Users: 
      Count: 1

  - Name: OrgB
    Domain: orgb.supermapchain.com
    Template:
      Count: 1
    Users: 
      Count: 1
